[site]
bucket = "./"
entry-point = "."

[site.static]
include = [
  "*.html",
  "*.css",
  "*.js",
  "*.json",
  "*.svg",
  "*.png",
  "*.ico",
  "icons/*"
]

[env.production]
name = "voice-assistant"
workers_dev = true
route = ""
zone_id = ""

# Update these values with your own Cloudflare account information
# account_id = "your-account-id"
