# Cloudflare Pages configuration
name = "assistant-agent-plugin"
compatibility_date = "2024-04-14"
compatibility_flags = ["nodejs_compat"]

# Specify the directory that should be deployed
pages_build_output_dir = "dist"

# Routes are handled by _redirects file
